### ISSUE TITLE
Be able to specify the winch driver

### ISSUE THREAD

**Issue by dan-corneanu** [tim-hogan/glidingops#1]
As operator I want to be able to record the name of the winch driver for each winch launch.
Acceptance criteria:
- [x] If the type of launch selected in the **PLANE** column is **WINCH** the list of options in the **TOW PILOT** column should only contain members with winch driver rating.

**Comment by dan-corneanu** [comment]
@tim-hogan 

1.By looking at the code I concluded that when an update for _**towpilotxml**_ or **_winchdriverxml_** is received from the backend, we do not update existing rows in the daily sheet, we only update rows that will be created from that moment on. Can you please confirm that this is correct?
2.Since the select in the **TOW PILOT** column switches between winch drivers and tow pilots, could we maybe rename it to something like **LAUNCH OPERATOR**?
3. On the same line of reasoning, could we maybe rename the **PLANE** column into **TYPE**? (entry type in the daily sheet)

What do you think?

**Comment by tim-hogan** [comment]
1. This is probably correct and should be corrected. Probably the reason was that the update of new Winch and Tow pilots was very unlikely during a day’s operation and I never got to coding it.
2. Agree, but think LAUNCH OPERATOR is too vague.  For people new to the entry and even experienced operators we need to articulate clearly that its either the TOW PILOT or WINCH OPERATOR.  I know real estate is always an issue but a heading with multiple lines that reads something like: TOW PILOT or WINCH DRIVER I thinks needs to be spelt out.
3. Agree, and again we need to think about who is running the tablet/PC.  Perhaps LAUNCH / PLANE or something like that.  

With cosmetic wording I think we need to run this against others, certainly Brian who has used and struggled sometimes with the tablet.

**Comment by dan-corneanu** [comment]
Ok, for 1. I will create a separate issue and address it after this one.
Regarding 2. and  3. I think you are right. I'll play a little bit with the CSS and see if I can come up with a column header layout to accomodate longer labels.

In the meantime, I have refactored the JS code around DailySheet a little bit and I've also changed it to update the content of the **TOW PILOT** dropdown according to the selection in the second column. It is not finished yet, it still needs to remember the current selection (in case we have members which are tow pilots and winch drivers, e.g. Tony Van Dyk), but you can already have a look and let me know what you think of these changes.

**Comment by tim-hogan** [comment]
Re both Tow Pilot and Winch drivers. In the drop down I think we need to remember who was selected before deleteing the list (e.g. from TOW to WINCH) and if they exists in both lists reselect them.
Currently Tony is not a Tow Pilot, The index is there memeber record id. Brian has just put him in there until we get this code working so, I dont think we actually have people that are both at the moment.

**Comment by dan-corneanu** [comment]
@tim-hogan  Why do we have dailysheet2.php too? I think it is not used. Can it be deleted?

**Comment by dan-corneanu** [comment]
Brian:
* LAUNCH PLANE rename to LAUNCH
* SELF -> TOW PILOT should be empty
* LAND -> empty tow pilot

**Comment by papajuliet** [comment]
Ok guys - tested in production and I'm happy - can be closed
